/* 
 * QuantiModo
 *
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Connector struct {

	// Connector ID number
	Id int32 `json:"id,omitempty"`

	// Connector lowercase system name
	Name string `json:"name,omitempty"`

	// Connector pretty display name
	DisplayName string `json:"displayName,omitempty"`

	// URL to the image of the connector logo
	Image string `json:"image,omitempty"`

	// URL to a site where one can get this device or application
	GetItUrl string `json:"getItUrl,omitempty"`

	// True if the authenticated user has this connector enabled
	Connected string `json:"connected,omitempty"`

	// URL and parameters used when connecting to a service
	ConnectInstructions string `json:"connectInstructions,omitempty"`

	// Epoch timestamp of last sync
	LastUpdate int32 `json:"lastUpdate,omitempty"`

	// Number of measurements obtained during latest update
	TotalMeasurementsInLastUpdate int32 `json:"totalMeasurementsInLastUpdate,omitempty"`
}
