/* 
 * QuantiModo
 *
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

import (
	"time"
)

type Correlation struct {

	// 
	AverageDailyLowCause float32 `json:"averageDailyLowCause,omitempty"`

	// 
	AverageDailyHighCause float32 `json:"averageDailyHighCause,omitempty"`

	// 
	AverageEffect float32 `json:"averageEffect,omitempty"`

	// 
	AverageEffectFollowingHighCause float32 `json:"averageEffectFollowingHighCause,omitempty"`

	// 
	AverageEffectFollowingLowCause float32 `json:"averageEffectFollowingLowCause,omitempty"`

	// 
	AverageEffectFollowingHighCauseExplanation string `json:"averageEffectFollowingHighCauseExplanation,omitempty"`

	// 
	AverageEffectFollowingLowCauseExplanation string `json:"averageEffectFollowingLowCauseExplanation,omitempty"`

	// Average Vote
	AverageVote float32 `json:"averageVote,omitempty"`

	// 
	CausalityFactor float32 `json:"causalityFactor,omitempty"`

	// Variable name of the cause variable for which the user desires correlations.
	Cause string `json:"cause,omitempty"`

	// Variable category of the cause variable.
	CauseVariableCategoryName string `json:"causeVariableCategoryName,omitempty"`

	// Number of changes in the predictor variable (a.k.a the number of experiments)
	CauseChanges int32 `json:"causeChanges,omitempty"`

	// The way cause measurements are aggregated
	CauseVariableCombinationOperation string `json:"causeVariableCombinationOperation,omitempty"`

	// 
	CauseVariableImageUrl string `json:"causeVariableImageUrl,omitempty"`

	// For use in Ionic apps
	CauseVariableIonIcon string `json:"causeVariableIonIcon,omitempty"`

	// Unit of the predictor variable
	CauseUnit string `json:"causeUnit,omitempty"`

	// Unit Id of the predictor variable
	CauseVariableDefaultUnitId int32 `json:"causeVariableDefaultUnitId,omitempty"`

	// 
	CauseVariableId int32 `json:"causeVariableId,omitempty"`

	// Variable name of the cause variable for which the user desires correlations.
	CauseVariableName string `json:"causeVariableName,omitempty"`

	// Pearson correlation coefficient between cause and effect measurements
	CorrelationCoefficient float32 `json:"correlationCoefficient,omitempty"`

	// When the record was first created. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// How the data was analyzed
	DataAnalysis string `json:"dataAnalysis,omitempty"`

	// How the data was obtained
	DataSources string `json:"dataSources,omitempty"`

	// The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
	DurationOfAction float32 `json:"durationOfAction,omitempty"`

	// Variable name of the effect variable for which the user desires correlations.
	Effect string `json:"effect,omitempty"`

	// Variable category of the effect variable.
	EffectVariableCategoryName string `json:"effectVariableCategoryName,omitempty"`

	// 
	EffectVariableImageUrl string `json:"effectVariableImageUrl,omitempty"`

	// For use in Ionic apps
	EffectVariableIonIcon string `json:"effectVariableIonIcon,omitempty"`

	// Magnitude of the effects of a cause indicating whether it's practically meaningful.
	EffectSize string `json:"effectSize,omitempty"`

	// Magnitude of the effects of a cause indicating whether it's practically meaningful.
	EffectVariableId string `json:"effectVariableId,omitempty"`

	// Variable name of the effect variable for which the user desires correlations.
	EffectVariableName string `json:"effectVariableName,omitempty"`

	// Illustrates the strength of the relationship
	GaugeImage string `json:"gaugeImage,omitempty"`

	// Large image for Facebook
	ImageUrl string `json:"imageUrl,omitempty"`

	// Number of points that went into the correlation calculation
	NumberOfPairs float32 `json:"numberOfPairs,omitempty"`

	// The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
	OnsetDelay float64 `json:"onsetDelay,omitempty"`

	// Optimal Pearson Product
	OptimalPearsonProduct float32 `json:"optimalPearsonProduct,omitempty"`

	// original name of the cause.
	OutcomeDataSources string `json:"outcomeDataSources,omitempty"`

	// HIGHER Remeron predicts HIGHER Overall Mood
	PredictorExplanation string `json:"predictorExplanation,omitempty"`

	// Mike Sinn
	PrincipalInvestigator string `json:"principalInvestigator,omitempty"`

	// Value representing the significance of the relationship as a function of crowdsourced insights, predictive strength, data quantity, and data quality
	QmScore float32 `json:"qmScore,omitempty"`

	// Correlation when cause and effect are reversed. For any causal relationship, the forward correlation should exceed the reverse correlation.
	ReverseCorrelation float32 `json:"reverseCorrelation,omitempty"`

	// Using a two-tailed t-test with alpha = 0.05, it was determined that the change...
	SignificanceExplanation string `json:"significanceExplanation,omitempty"`

	// A function of the effect size and sample size
	StatisticalSignificance string `json:"statisticalSignificance,omitempty"`

	// weak, moderate, strong
	StrengthLevel string `json:"strengthLevel,omitempty"`

	// These data suggest with a high degree of confidence...
	StudyAbstract string `json:"studyAbstract,omitempty"`

	// In order to reduce suffering through the advancement of human knowledge...
	StudyBackground string `json:"studyBackground,omitempty"`

	// This study is based on data donated by one QuantiModo user...
	StudyDesign string `json:"studyDesign,omitempty"`

	// As with any human experiment, it was impossible to control for all potentially confounding variables...
	StudyLimitations string `json:"studyLimitations,omitempty"`

	// Url for the interactive study within the web app
	StudyLinkDynamic string `json:"studyLinkDynamic,omitempty"`

	// Url for sharing the study on Facebook
	StudyLinkFacebook string `json:"studyLinkFacebook,omitempty"`

	// Url for sharing the study on Google+
	StudyLinkGoogle string `json:"studyLinkGoogle,omitempty"`

	// Url for sharing the study on Twitter
	StudyLinkTwitter string `json:"studyLinkTwitter,omitempty"`

	// Url for sharing the statically rendered study on social media
	StudyLinkStatic string `json:"studyLinkStatic,omitempty"`

	// The objective of this study is to determine...
	StudyObjective string `json:"studyObjective,omitempty"`

	// This analysis suggests that...
	StudyResults string `json:"studyResults,omitempty"`

	// N1 Study HIGHER Remeron predicts HIGHER Overall Mood
	StudyTitle string `json:"studyTitle,omitempty"`

	// Time at which correlation was calculated
	Timestamp float32 `json:"timestamp,omitempty"`

	// When the record in the database was last updated. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format. Time zone should be UTC and not local.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	// User Vote
	UserVote float32 `json:"userVote,omitempty"`

	// cause value that predicts an above average effect value (in default unit for cause variable)
	ValuePredictingHighOutcome float32 `json:"valuePredictingHighOutcome,omitempty"`

	// Overall Mood, on average, 34% HIGHER after around 3.98mg Remeron
	ValuePredictingHighOutcomeExplanation string `json:"valuePredictingHighOutcomeExplanation,omitempty"`

	// cause value that predicts a below average effect value (in default unit for cause variable)
	ValuePredictingLowOutcome float32 `json:"valuePredictingLowOutcome,omitempty"`

	// Overall Mood, on average, 4% LOWER after around 0mg Remeron
	ValuePredictingLowOutcomeExplanation string `json:"valuePredictingLowOutcomeExplanation,omitempty"`
}
