/* 
 * QuantiModo
 *
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Permission struct {

	// Grant permission to target user or public so they may access measurements within the given parameters. TODO: Rename target to something more intuitive.
	Target int32 `json:"target,omitempty"`

	// ORIGINAL Variable name
	VariableName string `json:"variableName,omitempty"`

	// Earliest time when measurements will be accessible in epoch seconds
	MinTimestamp int32 `json:"minTimestamp,omitempty"`

	// Latest time when measurements will be accessible in epoch seconds
	MaxTimestamp int32 `json:"maxTimestamp,omitempty"`

	// Earliest time of day when measurements will be accessible in epoch seconds
	MinTimeOfDay int32 `json:"minTimeOfDay,omitempty"`

	// Latest time of day when measurements will be accessible in epoch seconds
	MaxTimeOfDay int32 `json:"maxTimeOfDay,omitempty"`

	// Maybe specifies if only weekday measurements should be accessible
	Week string `json:"week,omitempty"`
}
