/* 
 * QuantiModo
 *
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type UserTag struct {

	// This is the id of the variable being tagged with an ingredient or something.
	TaggedVariableId int32 `json:"taggedVariableId,omitempty"`

	// This is the id of the ingredient variable whose value is determined based on the value of the tagged variable.
	TagVariableId int32 `json:"tagVariableId,omitempty"`

	// Number by which we multiply the tagged variable value to obtain the tag variable (ingredient) value
	ConversionFactor float32 `json:"conversionFactor,omitempty"`
}
