/* 
 * QuantiModo
 *
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type UserVariableRelationship struct {

	// id
	Id int32 `json:"id,omitempty"`

	// Our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors
	ConfidenceLevel string `json:"confidence_level,omitempty"`

	// A quantitative representation of our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors
	ConfidenceScore float32 `json:"confidence_score,omitempty"`

	// Direction is positive if higher predictor values generally precede higher outcome values. Direction is negative if higher predictor values generally precede lower outcome values.
	Direction string `json:"direction,omitempty"`

	// The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
	DurationOfAction int32 `json:"duration_of_action,omitempty"`

	// error_message
	ErrorMessage string `json:"error_message,omitempty"`

	// The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
	OnsetDelay int32 `json:"onset_delay,omitempty"`

	// Variable ID for the outcome variable
	OutcomeVariableId int32 `json:"outcome_variableId,omitempty"`

	// Variable ID for the predictor variable
	PredictorVariableId int32 `json:"predictor_variableId,omitempty"`

	// ID for default unit of the predictor variable
	PredictorUnitId int32 `json:"predictor_unit_id,omitempty"`

	// A value representative of the relevance of this predictor relative to other predictors of this outcome.  Usually used for relevancy sorting.
	SinnRank float32 `json:"sinn_rank,omitempty"`

	// Can be weak, medium, or strong based on the size of the effect which the predictor appears to have on the outcome relative to other variable relationship strength scores.
	StrengthLevel string `json:"strength_level,omitempty"`

	// A value represented to the size of the effect which the predictor appears to have on the outcome.
	StrengthScore float32 `json:"strength_score,omitempty"`

	// userId
	UserId int32 `json:"userId,omitempty"`

	// vote
	Vote string `json:"vote,omitempty"`

	// Value for the predictor variable (in it's default unit) which typically precedes an above average outcome value
	ValuePredictingHighOutcome float32 `json:"value_predicting_high_outcome,omitempty"`

	// Value for the predictor variable (in it's default unit) which typically precedes a below average outcome value
	ValuePredictingLowOutcome float32 `json:"value_predicting_low_outcome,omitempty"`
}
